protokol/nft

- LICENSE
- packages/nft-base-api/LICENSE
- packages/nft-base-api/README.md
- packages/nft-base-crypto/LICENSE
- packages/nft-base-crypto/README.md
- packages/nft-base-transactions/LICENSE
- packages/nft-base-transactions/README.md
- packages/nft-client/LICENSE
- packages/nft-client/README.md
- packages/nft-exchange-api/LICENSE
- packages/nft-exchange-api/README.md
- packages/nft-exchange-crypto/LICENSE
- packages/nft-exchange-crypto/README.md
- packages/nft-exchange-transactions/LICENSE
- packages/nft-exchange-transactions/README.md
- packages/nft-generator-api/LICENSE
- packages/nft-generator-api/README.md
> chore: license email updates

- packages/nft-exchange-api/src/controllers/auctions.ts
- packages/nft-exchange-api/src/controllers/bids.ts
- packages/nft-exchange-api/src/controllers/trades.ts
- packages/nft-exchange-api/src/routes/auctions.ts
- packages/nft-exchange-api/src/routes/bids.ts
> fix(nft-exchange-api): add transform parameter

- packages/nft-client/package.json
> chore(nft-client): bump version

- packages/nft-base-api/src/controllers/assets.ts
- packages/nft-base-api/src/controllers/collections.ts
- packages/nft-base-transactions/src/interfaces.ts
- packages/nft-exchange-api/src/controllers/auctions.ts
- packages/nft-exchange-api/src/controllers/bids.ts
- packages/nft-exchange-transactions/src/interfaces.ts
Improve responses for getting connected wallet endpoints. Closes https://github.com/protokol/nft-plugins/issues/88
> feat: improve get wallet endpoint responses

- .github/workflows/protokol-nft-tests.yml
- packages/nft-base-transactions/__tests__/functional/transaction-forging/nft-burn.test.ts
- packages/nft-base-transactions/__tests__/functional/transaction-forging/nft-create.test.ts
- packages/nft-base-transactions/__tests__/functional/transaction-forging/nft-register-collection.test.ts
- packages/nft-base-transactions/__tests__/functional/transaction-forging/nft-transfer.test.ts
- packages/nft-client/package.json
- packages/nft-client/src/resourcesTypes/exchange/configurations.ts
- packages/nft-client/src/resourcesTypes/exchange/index.ts
- packages/nft-exchange-transactions/__tests__/functional/transaction-forging/nft-accept-trade.test.ts
- packages/nft-exchange-transactions/__tests__/functional/transaction-forging/nft-auction-cancel.test.ts
- packages/nft-exchange-transactions/__tests__/functional/transaction-forging/nft-auction.test.ts
- packages/nft-exchange-transactions/__tests__/functional/transaction-forging/nft-bid-cancel.test.ts
- packages/nft-exchange-transactions/__tests__/functional/transaction-forging/nft-bid.test.ts
- packages/nft-exchange-transactions/__tests__/unit/handlers/nft-bid.test.ts
- packages/nft-exchange-transactions/src/defaults.ts
- Added more functional tests testing throwIfCannotBeApplied logic, pool logic, second passphrase wallet and multi signature wallet.
- remove safety distance from defaults because isn't used anymore
> test(nft-base-transactions + nft-exchange-transactions): added more functional tests

- packages/nft-base-transactions/src/handlers/nft-burn.ts
- packages/nft-base-transactions/src/handlers/nft-create.ts
- packages/nft-base-transactions/src/handlers/nft-register-collection.ts
- packages/nft-base-transactions/src/handlers/nft-transfer.ts
- packages/nft-exchange-transactions/src/handlers/nft-accept-trade.ts
- packages/nft-exchange-transactions/src/handlers/nft-auction-cancel.ts
- packages/nft-exchange-transactions/src/handlers/nft-auction.ts
- packages/nft-exchange-transactions/src/handlers/nft-bid-cancel.ts
- packages/nft-exchange-transactions/src/handlers/nft-bid.ts
Fix wallet repository indexing.
Removed some unnecessary indexing.
Some bugs are wallet-indexing related.
Replaced `forgetByIndex` method with `getIndex(index).forget(id)`
> fix(nft-base-transactions + nft-exchange-transactions): fix wallet repository indexing

- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-client/package.json
- packages/nft-examples/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- packages/nft-generator-api/package.json
- packages/nft-tx-tester/package.json
Add additional info section to all packages files. Closes https://github.com/protokol/nft-plugins/issues/107
Current package.json are missing some of additional information.
> docs(package.json): add additional info to packages

- packages/nft-base-api/src/routes/assets.ts
- packages/nft-base-api/src/routes/burns.ts
- packages/nft-base-api/src/routes/collections.ts
- packages/nft-base-api/src/routes/transfers.ts
- packages/nft-exchange-api/src/routes/auctions.ts
- packages/nft-exchange-api/src/routes/bids.ts
- packages/nft-exchange-api/src/routes/trades.ts
Update base and exchange API routes with plugin pagination configuration. Fixes https://github.com/protokol/nft-plugins/issues/117
To fix pagination due to change in v3 core introduced in https://github.com/ArkEcosystem/core/pull/3895
> feat(nft-base-api + nft-exchange-api): update pagination configuration

- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-client/package.json
- packages/nft-examples/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- packages/nft-generator-api/package.json
- packages/nft-tx-tester/package.json
- updated arkecosystem/core dependencies to alpha
- bump version of nft plugins
> chore: update to alpha dependencies and bump version

- package.json
> chore: root package ver bump

- packages/nft-client/src/resources/base/assets.ts
- packages/nft-client/src/resources/base/burns.ts
- packages/nft-client/src/resources/base/collections.ts
- packages/nft-client/src/resources/base/index.ts
- packages/nft-client/src/resources/base/transfers.ts
- packages/nft-client/src/resources/exchange/auctions.ts
- packages/nft-client/src/resources/exchange/bids.ts
- packages/nft-client/src/resourcesTypes/base/assets.ts
- packages/nft-client/src/resourcesTypes/base/burns.ts
- packages/nft-client/src/resourcesTypes/base/collections.ts
- packages/nft-client/src/resourcesTypes/base/transfers.ts
- packages/nft-client/src/resourcesTypes/exchange/auctions.ts
- packages/nft-client/src/resourcesTypes/exchange/bids.ts
- packages/nft-client/src/resourcesTypes/exchange/trades.ts
- packages/nft-client/src/resourcesTypes/timestamp.ts
- packages/nft-tx-tester/src/config/testnet/wallets.json
Added timestamp interface to all endpoints.
Making it possible to get the timestamp from endpoints.
> chore(nft-client): add timestamp to all endpoints

- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-examples/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- packages/nft-tx-tester/package.json
> release: version bump for crypto changes

- packages/nft-base-crypto/package.json
- packages/nft-base-crypto/src/transactions/nft-burn.ts
- packages/nft-base-crypto/src/transactions/nft-create.ts
- packages/nft-base-crypto/src/transactions/nft-register-collection.ts
- packages/nft-base-crypto/src/transactions/nft-transfer.ts
- packages/nft-examples/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-crypto/src/transactions/nft-accept-trade.ts
- packages/nft-exchange-crypto/src/transactions/nft-auction-cancel.ts
- packages/nft-exchange-crypto/src/transactions/nft-auction.ts
- packages/nft-exchange-crypto/src/transactions/nft-bid-cancel.ts
- packages/nft-exchange-crypto/src/transactions/nft-bid.ts
- packages/nft-exchange-transactions/package.json
- packages/nft-tx-tester/package.json
Further make more specific imports for core-kernel, since utils include some node packages
> refactor: more specific imports for core-kernel

- packages/nft-base-crypto/package.json
- packages/nft-base-crypto/rollup.config.js
- packages/nft-base-crypto/src/transactions/nft-transfer.ts
- packages/nft-exchange-crypto/package.json
- packages/utils/__tests__/unit/asserts/assert.test.ts
- packages/utils/package.json
- packages/utils/src/asserts/assert.ts
- packages/utils/src/index.ts
Browserify `nft-base-crypto` package
> feat(nft-base-crypto): browserify package

- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-crypto/src/index.ts
- packages/nft-base-transactions/package.json
- packages/nft-examples/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-crypto/src/index.ts
- packages/nft-exchange-transactions/package.json
- packages/nft-generator-api/package.json
- packages/nft-tx-tester/package.json
Expose `@arkecosystem/crypto` in crypto packages, for Electron easier development.
> chore: expose ark crypto

- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/ISSUE_TEMPLATE/2-feature-request.md
- .github/ISSUE_TEMPLATE/3-docs-bug.md
- CHANGELOG.md
- README.md
- package.json
- packages/nft-base-api/__tests__/unit/__support__/index.ts
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/__tests__/unit/__support__/app.ts
- packages/nft-base-transactions/package.json
- packages/nft-base-transactions/src/service-provider.ts
- packages/nft-client/package.json
- packages/nft-examples/package.json
- packages/nft-exchange-api/__tests__/unit/__support__/index.ts
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/__tests__/unit/__support__/app.ts
- packages/nft-exchange-transactions/package.json
- packages/nft-exchange-transactions/src/service-provider.ts
- packages/nft-generator-api/package.json
- packages/nft-tx-tester/package.json
- packages/utils/package.json
- sync with core changes
- autoindexers added
- prettier
> release: beta.22 release

- packages/nft-tx-tester/src/builder.ts
- packages/nft-tx-tester/src/commands/send/entity.ts
- packages/nft-tx-tester/src/config/config.ts
Updated support for AIP36 transactions - based on: https://github.com/ArkEcosystem/core-tx-tester/pull/30. Closes https://github.com/protokol/nft-plugins/issues/111
To support new transactions that were introduced in AIP36.
> fix(nft-tx-tester): update aip36 support

- README.md
- packages/guardian-crypto/README.md
- packages/guardian-transactions/README.md
- scripts/publish-beta.sh
> chore: adding guardian packages to publish script

- .github/workflows/protokol-nft-tests.yml
- packages/guardian-api/__tests__/integration/handlers/groups.test.ts
- packages/guardian-api/__tests__/integration/handlers/users.test.ts
- packages/guardian-api/__tests__/unit/__support__/index.ts
- packages/guardian-api/__tests__/unit/controllers/groups.test.ts
- packages/guardian-api/__tests__/unit/controllers/users.test.ts
- packages/guardian-transactions/__tests__/unit/__support__/app.ts
- packages/guardian-transactions/__tests__/unit/permission-resolver.test.ts
- packages/guardian-transactions/src/handlers/guardian-user-permissions.ts
- packages/guardian-transactions/src/service-provider.ts
- packages/nft-exchange-transactions/__tests__/unit/handlers/nft-auction-cancel.test.ts
Changed autoIndex in guardian plugins to false.
Updated branch for guardian tests.
To improve performance and index only properties that need to be indexed.
> chore(guardian): change autoIndex to false, update test branch

- package.json
- packages/client/package.json
- packages/examples/package.json
- packages/guardian-api/package.json
- packages/guardian-crypto/package.json
- packages/guardian-transactions/package.json
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- packages/nft-generator-api/package.json
- packages/nft-tx-tester/package.json
- packages/utils/package.json
Bump dependencies version and packages version.
To use the latest dependencies packages and prepare code for new package release.
> chore: bump package versions deps

- packages/client/src/connection-manager.ts
Replace typeof with instanceof
I figured it out that typeof works only with primitive types, so you have to check with instanceof
> fix(client): replace typeof with instanceof

- packages/guardian-api/__tests__/integration/handlers/groups.test.ts
- packages/guardian-api/__tests__/integration/handlers/users.test.ts
- packages/guardian-api/__tests__/unit/__support__/index.ts
- packages/guardian-api/__tests__/unit/controllers/groups.test.ts
- packages/guardian-api/__tests__/unit/controllers/users.test.ts
- packages/guardian-api/package.json
- packages/guardian-api/src/controllers/base-controller.ts
- packages/guardian-api/src/controllers/configurations.ts
- packages/guardian-api/src/controllers/groups.ts
- packages/guardian-api/src/controllers/users.ts
- packages/guardian-api/src/identifiers.ts
- packages/guardian-api/src/resources/groups.ts
- packages/guardian-api/src/resources/index.ts
- packages/guardian-api/src/resources/users.ts
- packages/guardian-api/src/routes/groups.ts
- packages/guardian-api/src/routes/users.ts
- packages/guardian-api/src/service-provider.ts
- packages/guardian-api/src/services/group-search-service.ts
- packages/guardian-api/src/services/index.ts
- packages/guardian-api/src/services/user-search-service.ts
Add pagination and orderBy (groups only) to groups and users endpoints.
CU-86u7n1
To allow a paginated view in GUI.
> feat(guardian-api): add pagination to groups/users endpoints

- package.json
- packages/cli/package.json
- packages/client/package.json
- packages/examples/package.json
- packages/guardian-api/package.json
- packages/guardian-crypto/package.json
- packages/guardian-transactions/package.json
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- packages/nft-generator-api/package.json
- packages/utils/package.json
- scripts/publish-beta.sh
Version bump to .25.
For new npm release.
> chore: version bump

- packages/client/src/resources-types/guardian/groups.ts
- packages/client/src/resources-types/guardian/index.ts
- packages/client/src/resources-types/guardian/users.ts
- packages/client/src/resources/guardian/groups.ts
- packages/client/src/resources/guardian/users.ts
- Added option for querying
- Fixed user interface
> fix(client): added option for querying and fixed user interface

- CHANGELOG.md
- package.json
> chore: change log and repo information

- packages/client/__tests__/mocks/nft/base/collections.ts
- packages/client/__tests__/resources/nft/base/collections.test.ts
- packages/client/src/resources-types/nft/base/collections.ts
Added missing allowedIssuers filed to collections
> fix(client): add missing allowedIssuers field

- packages/client/__tests__/connection/connection-manager.test.ts
- packages/client/__tests__/connection/connections.test.ts
- packages/client/__tests__/peer-discovery/peer-discovery.test.ts
- packages/client/__tests__/resources/guardian/groups.test.ts
- packages/client/__tests__/resources/guardian/users.test.ts
- packages/client/src/peer-discovery/peer-discovery.ts
- packages/client/src/resources/guardian/groups.ts
- packages/client/src/resources/guardian/users.ts
Updated types for users and groups.
Increased client test coverage to 100%.
Prevent unreachable code due to error catching.
CU-8jv9e6
To improve code coverage and fix types for client package usage.
> fix(client): user groups type update

- packages/client/src/resources-types/guardian/groups.ts
- packages/client/src/resources-types/guardian/users.ts
- packages/client/src/resources/guardian/users.ts
- packages/guardian-api/__tests__/unit/__support__/index.ts
- packages/guardian-api/__tests__/unit/controllers/groups.test.ts
- packages/guardian-api/__tests__/unit/controllers/users.test.ts
- packages/guardian-api/src/controllers/groups.ts
- packages/guardian-api/src/controllers/users.ts
- packages/guardian-api/src/resources/groups.ts
- packages/guardian-api/src/resources/index.ts
- packages/guardian-api/src/resources/users.ts
- packages/guardian-api/src/routes/groups.ts
- packages/guardian-api/src/routes/users.ts
- packages/guardian-api/src/services/group-search-service.ts
- packages/guardian-api/src/services/user-search-service.ts
- packages/guardian-crypto/src/builders/guardian-group-permissions.ts
- packages/guardian-crypto/src/builders/guardian-user-permissions.ts
- packages/guardian-crypto/src/interfaces.ts
- packages/guardian-crypto/src/transactions/guardian-group-permissions.ts
- packages/guardian-crypto/src/transactions/guardian-user-permissions.ts
- packages/guardian-transactions/__tests__/functional/transaction-forging/__support__/transaction-factory.ts
- packages/guardian-transactions/__tests__/unit/handlers/guardian-user-permissions.test.ts
- packages/guardian-transactions/src/handlers/guardian-group-permissions.ts
- packages/guardian-transactions/src/handlers/guardian-handler.ts
- packages/guardian-transactions/src/handlers/guardian-user-permissions.ts
- packages/guardian-transactions/src/interfaces.ts
Add searching by name, priority, default, active for groups.
Add searching by publicKey for users.
CU-8wrh1k
To allow searching and filtering users/groups results. This is especially appreciated on the frontend.
> feat(guardian): allow searching for groups/users

- package.json
- packages/cli/package.json
- packages/client/package.json
- packages/examples/package.json
- packages/guardian-api/package.json
- packages/guardian-crypto/package.json
- packages/guardian-transactions/package.json
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- packages/nft-generator-api/package.json
- packages/utils/package.json
Version bump to .27.
Ark core dependencies bump to .13.
CU-8pt2a3
To use latest ARK core changes and for new npm release.
> chore: plugin + dependencies bump

- packages/client/__tests__/mocks/guardian/configurations.ts
- packages/client/__tests__/resources/guardian/configurations.test.ts
- packages/guardian-api/__tests__/integration/handlers/custom-post-transactions.test.ts
Updated mocks based on the latest code changes.
Added test for forbidden error handling.
CU-90tvh4
To increase code coverage.
> test(client+guardian-api): forbidden error handling + client mock amend

- renovate.json
Dependabot config to preserve semver ranges.
To prevent deps pinning and to run dependabot on top of develop branch.
> chore: renovatebot preserve semver ranges

- .github/workflows/publish-beta.yml
- .pnp.js
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
To automate releases to npm. 
- chore: adding release to npm automation
- chore: bump version
> chore: adding release npm automation

- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> release: version bump

- .github/workflows/publish-beta.yml
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> Release bump

- .github/workflows/publish-beta.yml
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> chore: version bump for gha test

- .github/workflows/publish-beta.yml
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> fix: release - bump to beta.37

- .github/workflows/publish-beta.yml
- package.json
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- scripts/publish.sh
> fix: publish 

- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- scripts/publish.sh
- split automation deploy to use npm
- added back yarn2 publish scripts for local deployment
- version bump for test
> feat: automation deploy with npm, yarn2  local

- packages/nft-base-crypto/src/index.ts
- packages/nft-base-transactions/__tests__/functional/transaction-forging/nft-burn/multi-signature.test.ts
- packages/nft-base-transactions/__tests__/functional/transaction-forging/nft-burn/second-passphrase.test.ts
- packages/nft-base-transactions/__tests__/functional/transaction-forging/nft-burn/single-passphrase.test.ts
- packages/nft-exchange-crypto/src/index.ts
Remove ArkCrypto export from each package because it is no longer needed.
> fix(crypto): remove ArkCrypto export

- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> chore: bump packages version

- .pnp.js
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-crypto/src/transactions/nft-burn.ts
- packages/nft-base-crypto/src/transactions/nft-create.ts
- packages/nft-base-crypto/src/transactions/nft-register-collection.ts
- packages/nft-base-crypto/src/transactions/nft-transfer.ts
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-crypto/src/transactions/nft-accept-trade.ts
- packages/nft-exchange-crypto/src/transactions/nft-auction-cancel.ts
- packages/nft-exchange-crypto/src/transactions/nft-auction.ts
- packages/nft-exchange-crypto/src/transactions/nft-bid-cancel.ts
- packages/nft-exchange-crypto/src/transactions/nft-bid.ts
- packages/nft-exchange-transactions/package.json
- yarn.lock
Replaced `core-kernel` app utils with `@protokol/utils`.
Bump version.
`core-kernel` breaks browser build.
> chore(crypto): rollback @protokol/utils, replace core-kernel and bump version

- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> release: 1.0.0-beta.56

- README.md
> chore: update md links

- CHANGELOG.md
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> release: 1.0.0-beta.57

- CHANGELOG.md
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> release: 1.0.0 beta.58

- .pnp.js
- packages/nft-base-api/__tests__/integration/handlers/assets.test.ts
- packages/nft-base-api/__tests__/unit/__support__/index.ts
- packages/nft-base-api/__tests__/unit/controllers/assets.test.ts
- packages/nft-base-api/src/controllers/assets.ts
- packages/nft-base-api/src/routes/assets.ts
Added an endpoint that allows fetching all of the assets that the wallet has.
To easily fetch all of the user's assets on the frontend part of the application.
> feat(nft-base-api): get wallet's assets endpoint

- CHANGELOG.md
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> release: 1.0.0 beta.59

- packages/nft-base-api/src/routes/assets.ts
- packages/nft-base-crypto/src/transactions/nft-create.ts
- packages/nft-base-crypto/src/transactions/nft-register-collection.ts
Fix deserialization of strings that contain special characters.
Strings were not deserialized correctly if contained special chars leading to an error. This has been fixed.
> fix(nft-base-crypto): deserializing strings

- CHANGELOG.md
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> release: 1.0.0 beta.60

- CHANGELOG.md
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
> release: 1.0.0 beta.61

- CHANGELOG.md
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- packages/nft-indexer-api/package.json
> release: 1.0.0 beta.62

- packages/nft-indexer-api/__tests__/integration/handlers/auctions.test.ts
- packages/nft-indexer-api/__tests__/integration/handlers/configurations.test.ts
- packages/nft-indexer-api/__tests__/unit/controllers/configurations.test.ts
- packages/nft-indexer-api/package.json
- packages/nft-indexer-api/src/controllers/configurations.ts
- packages/nft-indexer-api/src/index.ts
- packages/nft-indexer-api/src/resources/configurations.ts
Enable returning version in configuration endpoints.
Export Enums
To also get the latest version when fetching configuration and to allow using Enums in client package
> feat(nft-indexer-api): enable configuration version

- CHANGELOG.md
- packages/nft-base-api/package.json
- packages/nft-base-crypto/package.json
- packages/nft-base-transactions/package.json
- packages/nft-exchange-api/package.json
- packages/nft-exchange-crypto/package.json
- packages/nft-exchange-transactions/package.json
- packages/nft-indexer-api/package.json
> release: 1.0.0 beta.63

- .github/workflows/unit.yml
- README.md
- packages/nft-base-api/README.md
- packages/nft-base-crypto/README.md
- packages/nft-base-transactions/README.md
- packages/nft-exchange-api/README.md
- packages/nft-exchange-crypto/README.md
- packages/nft-exchange-transactions/README.md
- packages/nft-indexer-api/README.md
> ci: setup codecov coverage

- .pnp.cjs
- packages/core-nft-crypto/LICENSE
- packages/core-nft-crypto/README.md
- packages/core-nft-crypto/jest.config.js
- packages/core-nft-crypto/package.json
- packages/core-nft-crypto/src/builders/abstract-builder.ts
- packages/core-nft-crypto/src/builders/index.ts
- packages/core-nft-crypto/src/index.ts
- packages/core-nft-crypto/src/transactions/abstract-transaction.ts
- packages/core-nft-crypto/src/transactions/index.ts
- packages/core-nft-crypto/tsconfig.json
- yarn.lock
Started working on refactoring of NFT story line.
Currently implemented abstract crypto package.
This will be followed with tests.
> feat(core-nft-crypto): setup abstract builder and abstract transaction

- .pnp.cjs
- packages/core-nft-crypto/__tests__/__mocks__/dummy.ts
- packages/core-nft-crypto/__tests__/unit/builders/abstract-builder.test.ts
- packages/core-nft-crypto/__tests__/unit/transactions/abstract-transaction.test.ts
- packages/core-nft-crypto/package.json
- yarn.lock
100% test coverage for core-nft-crypto.
> test(core-nft-crypto): 100% test coverage

- .github/workflows/unit.yml
- packages/core-nft-crypto/README.md
Setup ci and badges for core-nft-crypto.
> ci(core-nft-crypto): setup ci and badges
